- name: Ansible Clean
  ansible.builtin.apt:
    clean: yes
  become: "{{need_sudo}}"
- name: Remove files in /var/lib/apt/lists/
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: absent
  become: "{{need_sudo}}"
