- name: Prepare environment
  hosts: localhost
  gather_facts: false
  vars:
      ansible_python_interpreter: python3
  tasks:
    - name: Add docker container to inventory
      add_host:
        name: "{{docker_container}}"
        groups: docker_container_group
        ansible_connection: docker

- name: Setup DSS Docker Container
  hosts: docker_container_group
  gather_facts: false
  vars:
      ansible_python_interpreter: python3
      user_name: root
      user_home: /root
      need_sudo: false
      docker_integration_test: true
  tasks:
    - import_tasks: general_setup_tasks.yml
#     - name: Copy notebook content
#       ansible.builtin.copy:
#         src: "roles/jupyter/files/notebook/data/"
#         dest: /root/notebooks
#         mode: 0644
#     - name: Copy Entry Point Script
#       include_role:
#         name: entrypoint
    - import_tasks: cleanup_tasks.yml
