- name: Set facts for entry point
  vars:
    jupyter_virtualenv: "{{user_home}}/jupyterenv"
  ansible.builtin.set_fact:
    dss_facts:
      entrypoint: "{{user_home}}/entrypoint.py"
      jupyter:
        virtualenv: "{{ jupyter_virtualenv }}"
        command: "{{ jupyter_virtualenv }}/bin/jupyter-lab"
      notebook_folder:
        defaults: "{{user_home}}/notebook-defaults"
        final: "{{user_home}}/notebooks"
    cacheable: yes
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: "{{need_sudo}}"
- name: Install rsync
  include_role:
    name: rsync
- name: Install Poetry
  include_role:
    name: poetry
- name: Copy Entry Point Script
  include_role:
    name: entrypoint
- name: Install Jupyter
  include_role:
    name: jupyter
- name: Clear pip cache
  ansible.builtin.file:
    path: /root/.cache/pip
    state: absent
- name: Install Docker
  include_role:
    name: docker
