- name: Set New Default Password
  ansible.builtin.user:
    name: "{{ansible_user}}"
    state: present
    password: "{{ default_vm_password_hash }}"
    password_lock: no
  become: "{{need_sudo}}"

- name: Make Password Expired
  ansible.builtin.command: "passwd -e {{ansible_user}}"
  become: "{{need_sudo}}"

- name: Disable AWS Cloud Password Lock for User ubuntu
  become: "{{need_sudo}}"
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^(\s*)lock_passwd: True'
    line: '\1lock_passwd: False'
    state: present
    backrefs: yes

- name: Find SSH Config Files
  shell: ls /etc/ssh/sshd_config.d/* /etc/ssh/sshd_config
  register: ssh_config_files

# PasswordAuthentication needs to be "yes" in all relevant config files, see
# https://superuser.com/a/1828947.
#
# In this case KbdInteractiveAuthentication can be "no".
#
# Authentication via fabric/paramiko in Python test cases in
# test/codebuild/test_ci.py also requires genuine password authentication and
# fails when having only keyboard-interactive authentication.

- name: Enable SSH Password Authentication
  become: "{{need_sudo}}"
  lineinfile:
    dest: "{{ item }}"
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication yes'
    state: present
  with_items: "{{ ssh_config_files.stdout_lines }}"

- name: Remove .ssh Directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: absent

- name: Restart sshd
  become: "{{need_sudo}}"
  service:
    name: sshd
    state: restarted
