- name: Reset passwords
  hosts: ec2
  vars:
      ansible_python_interpreter: /usr/bin/python3
      user_name: ubuntu
      user_home: /home/ubuntu
      need_sudo: yes
  remote_user: ubuntu
  tasks:
  - import_tasks: reset_password_tasks.yml
