- name: Set New Default Password
  ansible.builtin.user:
    name: "{{ansible_user}}"
    state: present
    password: "{{ default_vm_password }}"
    password_lock: no
  become: "{{need_sudo}}"

- name: Make Password Expired
  ansible.builtin.command: "passwd -e {{ansible_user}}"
  become: "{{need_sudo}}"

- name: Disable AWS Cloud Password Lock for User ubuntu
  become: "{{need_sudo}}"
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^(\s*)lock_passwd: True'
    line: '\1lock_passwd: False'
    state: present
    backrefs: yes

- name: Enable SSH Password Authentication
  become: "{{need_sudo}}"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication yes'
    state: present

- name: Enable SSH Keyboard Interactive Authentication
  become: "{{need_sudo}}"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*KbdInteractiveAuthentication\s'
    line: 'KbdInteractiveAuthentication yes'
    state: present

- name: Remove .ssh Directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: absent

- name: Restart sshd
  become: "{{need_sudo}}"
  service:
    name: sshd
    state: restarted
