---

jupyterlab_ip: '*'
jupyterlab_config: "{{user_home}}/.jupyter/jupyter_lab_config.py"

# overridden in include_role
jupyterlab_virtualenv: "{{ user_home }}/jupyterenv"
jupyterlab_command: "{{ jupyterlab_virtualenv }}/bin/jupyter-lab"
jupyterlab_password: "{{ lookup('ansible.builtin.env', 'JUPYTER_LAB_PASSWORD', default='dss') }}"
jupyterlab_notebook_folder_initial: "{{ user_home }}/notebooks"
jupyterlab_notebook_folder: "{{ user_home }}/notebooks"

apt_dependencies:
  - rsync=3.1.3-8ubuntu0.7
  - virtualenv=20.0.17-1ubuntu0.4
  - git=1:2.25.1-1ubuntu3.11
