---

jupyterlab_ip: '*'
# Setting environment variable $HOME to {{user_home}} forces the directory for
# creating the config file.  Unfortunately this does not affect the json file.
jupyterlab_config: "{{user_home}}/.jupyter/jupyter_lab_config.py"
# jupyterlab_config_json: "{{ansible_env.HOME}}/.jupyter/jupyter_server_config.json"
jupyterlab_config_json: "{{user_home}}/.jupyter/jupyter_server_config.json"
jupyterlab_default_url: "/lab/tree/start.ipynb"

# overridden in include_role
jupyterlab_virtualenv: "{{ user_home }}/jupyterenv"
jupyterlab_command: "{{ jupyterlab_virtualenv }}/bin/jupyter-lab"
jupyterlab_password: "{{ lookup('ansible.builtin.env', 'JUPYTER_LAB_PASSWORD', default='ai-lab') }}"
jupyterlab_notebook_folder_initial: "{{ user_home }}/notebooks"
jupyterlab_notebook_folder: "{{ user_home }}/notebooks"

apt_dependencies:
  - virtualenv=20.0.17-1ubuntu0.4
  - git=1:2.25.1-1ubuntu3.11
