---

jupyterlab_ip: '*'
jupyterlab_config: "{{user_home}}/.jupyter/jupyter_lab_config.py"

# overridden in include_role
jupyterlab_virtualenv: "{{user_home}}/jupyterenv"
jupyterlab_command: "{{ jupyterlab_virtualenv }}/bin/jupyter-lab"
jupyterlab_password: "{{ lookup('ansible.builtin.env', 'JUPYTER_LAB_PASSWORD', default='dss') }}"
jupyterlab_notebook_folder: "/root/notebooks"

apt_dependencies:
  - rsync=3.1.3-8ubuntu0.7
  - virtualenv=20.0.17-1ubuntu0.4
