version: 0.2

env:
  shell: bash
  variables:
    DEFAULT_PASSWORD: "dss"
    ASSET_ID: ""
    AWS_USER_NAME: "release_user"
    MAKE_AMI_PUBLIC_OPTION: "--no-make-ami-public"
  secrets-manager:
    DOCKER_REGISTRY_USER: "Dockerhub:User"
    DOCKER_REGISTRY_PASSWORD: "Dockerhub:AccessToken"

phases:

  install:
    runtime-versions:
      python: 3.8
    commands:
      - git submodule update --init --recursive
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.local/bin
      - poetry env use $(command -v "python3.8")
      - poetry install

  pre_build:
      commands:
        - echo ASSET_ID is "$ASSET_ID"
        - echo DEFAULT_PASSWORD is "$DEFAULT_PASSWORD"
        - echo RELEASE_ID is "$RELEASE_ID"
        - echo MAKE_AMI_PUBLIC_OPTION is "$MAKE_AMI_PUBLIC_OPTION"
  build:
      commands:
        - poetry run python3 -m exasol.ds.sandbox.main create-vm --default-password "$DEFAULT_PASSWORD" --asset-id "$ASSET_ID" $MAKE_AMI_PUBLIC_OPTION
        - poetry run python3 -m exasol.ds.sandbox.main create-docker-image --version "$ASSET_ID" --publish --log-level info
        - poetry run python3 -m exasol.ds.sandbox.main update-release --release-id "$RELEASE_ID" --asset-id "$ASSET_ID"
