#!/usr/bin/env python3

import pathlib
import json

motd_message = """
Server for Jupyter has been started successfully.

You can connect with https://<host>:{{jupyterlab_port}}.

{{heading_jupyter_update_password}}

The default password is "{{jupyterlab_password}}".
To update the password run as user {{ user_name }} the following command
    {{jupyterlab_virtualenv}}/bin/jupyter server password
"""

server_config_file = pathlib.Path("{{jupyterlab_config_json}}")

if server_config_file.exists():
    with open(server_config_file) as f:
        hashed_server_password = json.load(f)["IdentityProvider"]["hashed_password"]
    # server_hashed_password was set by ansible (see motd.yml)
    if hashed_server_password == "{{jupyter_server_hashed_password}}":
        print(motd_message)
