Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            - Effect: Allow
              Principal:
                  Service:
                    - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole
      Description: !Sub "IAM Role for ${AWS::StackName}"
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - logs:*
                Resource: "*"
                Effect: Allow
              - Action:
                - cloudformation:DescribeStacks
                - cloudformation:ListStacks
                - cloudformation:ListStackResources
                Resource: "*"
                Effect: Allow
              - Action:
                - cloudformation:CreateChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:DeleteStack
                Resource: !Sub  "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/stack-ci-test-*"
                Effect: Allow
              - Action:
                - ec2:CreateSecurityGroup
                - ec2:DeleteSecurityGroup
                - ec2:AuthorizeSecurityGroupIngress
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*"
                Effect: Allow
              - Action:
                - ec2:RunInstances
                - ec2:TerminateInstances
                - ec2:DescribeInstances
                - ec2:CreateTags
                - ec2:DescribeImages
                - ec2:DescribeSnapshots
                - ec2:DescribeSecurityGroups
                - ec2:DescribeExportImageTasks
                - ec2:DescribeKeyPairs
                - ec2:DescribeInstanceStatus
                - ec2:CreateImage
                - ec2:DeregisterImage
                - ec2:DeleteSnapshot
                Resource: "*"
                Effect: Allow
              - Action:
                - ec2:CreateKeyPair
                - ec2:DeleteKeyPair
                Resource: !Sub  "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:key-pair/ec2-key-*"
                Effect: Allow
              - Action:
                - s3:ListBucket
                Resource: arn:aws:s3:::{{vm_bucket}}
                Effect: Allow
              - Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                Resource: arn:aws:s3:::{{vm_bucket}}/*
                Effect: Allow
  DataScienceSandboxCICodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: CI Build which runs CI test of the ai-lab
      Triggers:
        Webhook: True
        FilterGroups:
          -  - Type: EVENT
               Pattern: PUSH
             - Type: HEAD_REF
               Pattern: ^refs/heads/main$
               ExcludeMatchedPattern: true
             - Type: COMMIT_MESSAGE
               Pattern: \[CodeBuild\]
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: GITHUB
        Location: "https://github.com/exasol/ai-lab"
        BuildSpec: "aws-code-build/ci/buildspec.yaml"
      TimeoutInMinutes: 240

#Trick to have log retention, see https://medium.com/allermedia-techblog/cloudformation-example-log-retention-for-lambda-and-codebuild-a11e74516bb6
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/codebuild/${ DataScienceSandboxCICodeBuild }"
      RetentionInDays: 14

Outputs:
  ProjectName:
    Value: !Ref DataScienceSandboxCICodeBuild
    Description: Developer Sandbox CI Build project name
