Resources:
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Instance access
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          # literal value to be replaced by variable in ticket #140
          FromPort: 49494
          IpProtocol: tcp
          ToPort: 49494
      Tags:
        - Key: "exasol:project"
          Value: "DataScienceSandbox"
        - Key: "exasol:owner"
          Value: {{user_name}}
        - Key: {{trace_tag}}
          Value: {{trace_tag_value}}

  EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
          ImageId: {{ami_id}}
          KeyName: {{key_name}}
          InstanceType: "t2.medium"
          SecurityGroups:
          - !Ref Ec2SecurityGroup
          BlockDeviceMappings:
          -
            DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100
          Tags:
            - Key: "exasol:project"
              Value: "DataScienceSandbox"
            - Key: "exasol:owner"
              Value: {{user_name}}
            - Key: {{trace_tag}}
              Value: {{trace_tag_value}}

