---

- name: Copy pip requirements file
  ansible.builtin.copy:
    src: "{{pip_requirements_file}}"
    dest: "/tmp/{{pip_requirements_file}}"
    mode: 0644
  register: pip_requirements_file_loc

- name: Install Python packages via pip
  ansible.builtin.pip:
    requirements: "{{ pip_requirements_file_loc.dest }}"
    state: latest
    virtualenv: "{{jupyterlab.virtualenv}}"
    virtualenv_python: python3.8

- name: Remove the requirements file (delete file)
  ansible.builtin.file:
    path: "{{ pip_requirements_file_loc.dest }}"
    state: absent
