---

- name: Copy requirements file {{ pip_requirements_file }}
  ansible.builtin.copy:
    src: "{{pip_requirements_file}}"
    dest: "/tmp/{{pip_requirements_file}}"
    mode: 0644
  register: pip_requirements_file_loc

- name: Call pip install {{ pip_requirements_file }}
  ansible.builtin.pip:
    requirements: "{{ pip_requirements_file_loc.dest }}"
    state: latest
    virtualenv: "{{jupyterlab_virtualenv}}"
    virtualenv_python: python3.8
  become: "{{need_sudo}}"

- name: Remove requirements file {{ pip_requirements_file }}
  ansible.builtin.file:
    path: "{{ pip_requirements_file_loc.dest }}"
    state: absent
