---

# because the generate-config command below never overwrites an existing file
- name: Delete existing JupyterLab config file
  ansible.builtin.file:
    path: "{{ jupyterlab_config }}"
    state: absent
  become: "{{ need_sudo }}"

# it generates file ~/.jupyter/jupyter_lab_config.py
# - the config file is very large (>30K)
# - it has all rows commented out
#
# Set environment variable $HOME to {{user_home}} to force the directory for
# creating the config file.
- name: Generate JupyterLab config
  ansible.builtin.command: "{{jupyterlab_virtualenv}}/bin/jupyter lab --generate-config"
  environment:
    HOME: "{{ user_home }}"
  become: "{{ need_sudo }}"

- name: Edit JupyterLab config with our settings
  ansible.builtin.lineinfile:
    path: "{{ jupyterlab_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "c.NotebookApp.ip"
      line: "c.NotebookApp.ip = '{{ jupyterlab_ip }}'"
    - regexp: "c.NotebookApp.open_browser"
      line: "c.NotebookApp.open_browser = False"
    - regexp: "c.LabApp.default_url"
      line: "c.LabApp.default_url = '{{ jupyterlab_default_url }}'"
    - regexp: "c.ServerApp.port"
      line: "c.ServerApp.port = {{ jupyterlab_port }}"
  become: "{{ need_sudo }}"

# Set environment variable $HOME to {{user_home}} to force the directory for
# creating the file jupyter_server_config.json.
- name: Generate a new password
  expect:
    command: "{{jupyterlab_virtualenv}}/bin/jupyter server password"
    responses:
      Enter password: "{{jupyterlab_password}}"
      Verify password: "{{jupyterlab_password}}"
  environment:
    HOME: "{{ user_home }}"
  become: "{{ need_sudo }}"

- name: Create the notebook directory
  ansible.builtin.file:
    path: "{{ dss_facts.notebook_folder.initial }}"
    state: directory
    mode: '0755'
  become: "{{ need_sudo }}"
