---

- name: Update pip version
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{jupyterlab_virtualenv}}"
    virtualenv_python: python3.8
    extra_args: "--upgrade"
  become: "{{need_sudo}}"
