- name: Set facts for later discovery
  ansible.builtin.set_fact:
    dss_ansible_facts:
      entrypoint: "{{entrypoint_script}}"
    cacheable: yes
- name: Copy entrypoint script
  ansible.builtin.copy:
    src: "entrypoint.py"
    dest: "{{entrypoint_script}}"
    mode: 0644
