---

- name: Install dependant apt packages
  apt:
    name: "{{apt_dependencies}}"
    state: present
    update_cache: yes
  become: "{{need_sudo}}"
- name: Install Poetry
  shell: "curl -sSL https://install.python-poetry.org | python3 - -y"
