---


- name: Setup Jupyter
  block:
    - name: Install dependant apt packages
      apt:
        name: "{{apt_dependencies}}"
        state: present
      become: "{{need_sudo}}"

    - name: Install JupyterLab and its dependencies
      include_tasks:
        file: install-pip-packages.yml
      vars:
        - pip_requirements_file: "requirements_jupyter.txt"

    - name: Setup Jupyterlab
      ansible.builtin.import_tasks: jupyterlab.yml

    - name: Install dependencies used in Jupyterlab
      include_tasks:
        file: install-pip-packages.yml
      vars:
        - pip_requirements_file: "requirements_dependencies.txt"

    - name: Setup Systemd service
      ansible.builtin.import_tasks: systemd.yml

    - name: Copy tutorial notebook
      ansible.builtin.import_tasks: tutorial.yml

    - name: Setup motd
      ansible.builtin.import_tasks: motd.yml

