name: Check Notebook Links

on:
  push:
    branches-ignore:
      - "main"

jobs:
  check_notebook_links:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Setup Python & Poetry Environment
       uses: exasol/python-toolbox/.github/actions/python-environment@0.13.0
       with:
         python-version: "3.10"
         poetry-version: '1.8.2'

     - name: Run build ai-lab tests
       run: >
         poetry run pytest --check-links exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/

