name: Check Notebook Links

on:
  push:
    branches-ignore:
      - "main"

jobs:
  check_notebook_links:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup Python & Poetry Environment
       uses: ./.github/actions/prepare_poetry_env

     - name: Run build ai-lab tests
       run: >
         poetry run pytest --check-links exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/

