name: Run Tests for CI Build

on:
  push:
    branches-ignore:
      - "main"

jobs:
  run_build_ai_lab_tests:
    environment: AWS_CI_TESTS
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup Python & Poetry Environment
       uses: ./.github/actions/prepare_poetry_env

     - name: Show commit message
       run: echo ${{ github.event.head_commit.message }}

     - name: Run build ai-lab tests
       run: >
         poetry run pytest
         --capture=no
         --override-ini=log_cli=true
         --override-ini=log_cli_level=INFO
         test/unit
         test/integration
       env: # Set the secret as an env variable
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  run_nodebook_tests:
    # if: "contains(github.event.head_commit.message, '[run-notebook-tests]')"
    environment: AWS_SAGEMAKER
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Free disk space
       uses: jlumbroso/free-disk-space@main
       with:
         tool-cache: true
         large-packages: false

     - name: Free disk space by removing large directories
       run: |
         sudo rm -rf /usr/local/graalvm/
         sudo rm -rf /usr/local/.ghcup/
         sudo rm -rf /usr/local/share/powershell
         sudo rm -rf /usr/local/share/chromium
         sudo rm -rf /usr/local/lib/node_modules
         sudo rm -rf /opt/ghc

     - name: Setup Python & Poetry Environment
       uses: ./.github/actions/prepare_poetry_env

     - name: Run notebook tests
       run: >
         poetry run pytest
         --capture=no
         --override-ini=log_cli=true
         --override-ini=log_cli_level=INFO
         test/notebook_test_runner/test_notebooks_in_dss_docker_image.py
       env: # Set the secret as an env variable
         NBTEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         NBTEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
         NBTEST_AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
