name: CI

on:
  pull_request:

jobs:
  run-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04

    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Run shellcheck
       run: ./scripts/build/shellcheck.sh

     - name: Setup Python & Poetry Environment
       uses: exasol/python-toolbox/.github/actions/python-environment@1.0.0
       with:
         python-version: "3.10"

     - name: Check Version Number
       run: poetry run -- python3 -u "./scripts/build/check_release.py"

     - name: Run Unit Tests
       run: >
         poetry run -- pytest
         --capture=no
         --override-ini=log_cli=true
         --override-ini=log_cli_level=INFO
         test/unit

  run-integration-tests:
    name: Integration Tests
    environment: AWS_CI_TESTS
    runs-on: ubuntu-24.04
    needs: run-unit-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare_test_env/

      - name: Run Integration Tests
        run: >
          poetry run -- pytest
          --capture=no
          --override-ini=log_cli=true
          --override-ini=log_cli_level=INFO
          test/integration
        env: # Set the secret as an env variable
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
         AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  approval-for-notebook-tests:
    name: Run Jupyter Notebook Tests?
    runs-on: ubuntu-24.04
    steps:
      - name: Detect Running Notebook Tests
        run: true
    environment:
      approve-test-execution

  run-notebook-tests:
    uses: ./.github/workflows/notebook_tests.yaml
    secrets: inherit
    needs: approval-for-notebook-tests

  gate-2:
    name: Gate 2 - Allow Merge
    runs-on: ubuntu-24.04
    needs: [ run-unit-tests, run-integration-tests, run-notebook-tests ]
    steps:
      - name: Branch Protection
        run: true
