name: Notebook Docker Image Builder

on:
  workflow_call:
jobs:
  notebook-tests-docker-image-builder:
    runs-on: ubuntu-24.04
    name: Running Build Docker image
    env:
      DOCKER_TAG: "${{ github.sha }}"
      DOCKER_IMG_ARTIFACT: "ai-lab-${{ github.sha }}"
      DOCKER_IMG_FILENAME: "ai-lab-${{ github.sha }}.tar"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare_test_env/
      - name: Create Docker Image
        run: poetry run ai-lab create-docker-image --version "$DOCKER_TAG" --log-level info
      - name: Export docker image
        run: docker save -o "./$DOCKER_IMG_FILENAME" "exasol/ai-lab:$DOCKER_TAG"
      - uses: actions/upload-artifact@v4
        name: Upload ai-lab docker image
        with:
          name: "${{ env.DOCKER_IMG_ARTIFACT }}"
          path: "./${{ env.DOCKER_IMG_FILENAME }}"
          compression-level: 5
          retention-days: 1
