name: Notebook Tests

on:
  workflow_call:

jobs:
  notebook-tests-docker-image-builder:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        wip: [no-wip, wip]
    name: Running Build Docker image - ${{ matrix.wip }}
    env:
      DOCKER_TAG: "${{ matrix.wip }}-${{ github.sha }}"
      DOCKER_IMG_ARTIFACT: "ai-lab-${{ matrix.wip }}-${{ github.sha }}"
      DOCKER_IMG_FILENAME: "ai-lab-${{ matrix.wip }}-${{ github.sha }}.tar"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare_test_env/
      - name: Run notebook tests
        run: |
            additional_options=""
            if [[ "${{ matrix.wip }}" == "wip" ]]; then
              additional_options="--work-in-progress-notebooks"
            fi
            poetry run ai-lab create-docker-image --version "$DOCKER_TAG" --log-level info $additional_options
      - name: Export docker image
        run: docker save -o "./$DOCKER_IMG_FILENAME" "exasol/ai-lab:$DOCKER_TAG"
      - uses: actions/upload-artifact@v4
        name: Upload ai-lab docker image
        with:
          name: "${{ env.DOCKER_IMG_ARTIFACT }}"
          path: "./${{ env.DOCKER_IMG_FILENAME }}"
          compression-level: 5
          retention-days: 1

  notebook_tests-normal-runner:
    needs: [notebook-tests-docker-image-builder]
    environment: AWS_SAGEMAKER
    runs-on: ubuntu-24.04
    env:
      DOCKER_TAG: "${{ matrix.nb_test.wip }}-${{ github.sha }}"
      DOCKER_IMG_ARTIFACT: "ai-lab-${{ matrix.nb_test.wip }}-${{ github.sha }}"
      DOCKER_IMG_FILENAME: "ai-lab-${{ matrix.nb_test.wip }}-${{ github.sha }}.tar"
    strategy:
      fail-fast: false
      matrix:
        nb_test:
          - { name: "CSE notebook", test_file: "nbtest_cloud.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
          - { name: "CSE notebook", test_file: "nbtest_cloud.py", test_backend: "saas", wip: "no-wip", "test_status": "stable" }
          - { name: "sklearn notebook", test_file: "nbtest_sklearn.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
          - { name: "sklearn notebook", test_file: "nbtest_sklearn.py", test_backend: "saas", wip: "no-wip", "test_status": "unstable" }
          - { name: "ibis notebook", test_file: "nbtest_ibis.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
          - { name: "ibis notebook", test_file: "nbtest_ibis.py", test_backend: "saas", wip: "no-wip", "test_status": "unstable" }
#          - { name: "SLC notebook", test_file: "nbtest_script_languages_container.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
#          - { name: "SME notebooks", test_file: "nbtest_sagemaker.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
#          - { name: "SME notebooks", test_file: "nbtest_sagemaker.py", test_backend: "saas", wip: "no-wip", "test_status": "unstable" }
#          - { name: "TE notebooks", test_file: "nbtest_transformers.py", test_backend: "onprem", wip: "no-wip", "test_status": "stable" }
#          - { name: "TE notebooks", test_file: "nbtest_transformers.py", test_backend: "saas", wip: "no-wip", "test_status": "unstable" }
          - { name: "short notebook tests", test_file: "\"nbtest_environment_test.py nbtest_itde.py\"", test_backend: "", wip: "no-wip", "test_status": "stable" }
#          - { name: "TXAIE notebooks", test_file: "nbtest_text_ai.py", test_backend: "saas", wip: "no-wip", "test_status": "unstable" }
    name: Running ${{ matrix.nb_test.name }} - ${{ matrix.nb_test.test_backend }}
    continue-on-error: ${{ matrix.nb_test.test_status == 'unstable' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare_test_env/

      - name: Download ai-lab image ${{matrix.nb_test.wip}}
        id: download-image
        uses: actions/download-artifact@v5
        with:
          name: "${{ env.DOCKER_IMG_ARTIFACT }}"
          path: "."

      - name: Load ai-lab image ${{matrix.nb_test.wip}}
        run: docker load -i "./$DOCKER_IMG_FILENAME"

      - name: Run notebook tests
        run: |
          poetry run -- pytest \
            --capture=no \
            --override-ini=log_cli=true \
            --override-ini=log_cli_level=INFO \
            --dss-docker-image="exasol/ai-lab:$DOCKER_TAG" \
            --nb-test-backend=${{ matrix.nb_test.test_backend }} \
            --nb-test-file=${{ matrix.nb_test.test_file }} \
            test/notebook_test_runner/test_notebooks_in_dss_docker_image.py
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
          NBTEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          NBTEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          NBTEST_AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          NBTEST_TXAIE_ZIP_URL: ${{ vars.TXAIE_ZIP_URL }}
          NBTEST_TXAIE_ZIP_PASSWORD: ${{ secrets.TXAIE_ZIP_PASSWORD }}
          PROJECT_SHORT_TAG: XAIL-NB

  notebook_tests-large-runner:
    needs: [notebook-tests-docker-image-builder]
    environment: AWS_SAGEMAKER
    env:
      DOCKER_TAG: "${{ matrix.nb_test.wip }}-${{ github.sha }}"
      DOCKER_IMG_ARTIFACT: "ai-lab-${{ matrix.nb_test.wip }}-${{ github.sha }}"
      DOCKER_IMG_FILENAME: "ai-lab-${{ matrix.nb_test.wip }}-${{ github.sha }}.tar"
    runs-on:
      labels: int-linux-x64-4core-ubuntu24.04-1
    strategy:
      fail-fast: false
      matrix:
        nb_test:
          - { name: "TXAIE notebooks onprem", test_file: "nbtest_text_ai.py", test_backend: "onprem", wip: "no-wip"}
    name: Running ${{ matrix.nb_test.name }} - ${{ matrix.nb_test.test_backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare_test_env/

      - name: Download ai-lab image ${{matrix.nb_test.wip}}
        id: download-image
        uses: actions/download-artifact@v5
        with:
          name: "${{ env.DOCKER_IMG_ARTIFACT }}"
          path: "."

      - name: Load ai-lab image ${{matrix.nb_test.wip}}
        run: docker load -i "./$DOCKER_IMG_FILENAME"

      - name: Run notebook tests
        run: |
          poetry run pytest \
            --capture=no \
            --override-ini=log_cli=true \
            --override-ini=log_cli_level=INFO \
            --dss-docker-image="exasol/ai-lab:$DOCKER_TAG" \
            --nb-test-backend=${{ matrix.nb_test.test_backend }} \
            --nb-test-file=${{ matrix.nb_test.test_file }} \
            --nb-test-db-mem-size="8 GiB" \
            test/notebook_test_runner/test_notebooks_in_dss_docker_image.py
        env:
          NBTEST_TXAIE_ZIP_URL: ${{ vars.TXAIE_ZIP_URL }}
          NBTEST_TXAIE_ZIP_PASSWORD: ${{ secrets.TXAIE_ZIP_PASSWORD }}
          PROJECT_SHORT_TAG: XAIL-NB
