name: Notebook Docker Image Builder

on:
  workflow_call:
jobs:
  notebook-tests-docker-image-builder:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        wip: [no-wip, wip]
    name: Running Build Docker image - ${{ matrix.wip }}
    env:
      DOCKER_TAG: "${{ matrix.wip }}-${{ github.sha }}"
      DOCKER_IMG_ARTIFACT: "ai-lab-${{ matrix.wip }}-${{ github.sha }}"
      DOCKER_IMG_FILENAME: "ai-lab-${{ matrix.wip }}-${{ github.sha }}.tar"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare_test_env/
      - name: Create Docker Image
        run: |
            additional_options=""
            if [[ "${{ matrix.wip }}" == "wip" ]]; then
              additional_options="--work-in-progress-notebooks"
            fi
            poetry run ai-lab create-docker-image --version "$DOCKER_TAG" --log-level info $additional_options
      - name: Export docker image
        run: docker save -o "./$DOCKER_IMG_FILENAME" "exasol/ai-lab:$DOCKER_TAG"
      - uses: actions/upload-artifact@v4
        name: Upload ai-lab docker image
        with:
          name: "${{ env.DOCKER_IMG_ARTIFACT }}"
          path: "./${{ env.DOCKER_IMG_FILENAME }}"
          compression-level: 5
          retention-days: 1
