- name: set new default password
  ansible.builtin.user:
    name: "{{ansible_user}}"
    state: present
    password: "{{ default_vm_password | password_hash('sha512') }}"
  become: "{{need_sudo}}"

- name: make password expired
  ansible.builtin.command: "passwd -e {{ansible_user}}"
  become: "{{need_sudo}}"

- name: Enable SSH password authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication yes'
    state: present

- name: remove .ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: absent

- name: Restart ssh
  become: "{{need_sudo}}"
  service:
    name: sshd
    state: restarted
